//
// Created by claunia on 17/03/19.
//

#ifndef LIBAARUFORMAT_ERRORS_H
#define LIBAARUFORMAT_ERRORS_H

#define AARUF_ERROR_NOT_AARUFORMAT -1
#define AARUF_ERROR_FILE_TOO_SMALL -2
#define AARUF_ERROR_INCOMPATIBLE_VERSION -3
#define AARUF_ERROR_CANNOT_READ_INDEX -4
#define AARUF_ERROR_SECTOR_OUT_OF_BOUNDS -5
#define AARUF_ERROR_CANNOT_READ_HEADER -6
#define AARUF_ERROR_CANNOT_READ_BLOCK -7
#define AARUF_ERROR_UNSUPPORTED_COMPRESSION -8
#define AARUF_ERROR_NOT_ENOUGH_MEMORY -9
#define AARUF_ERROR_BUFFER_TOO_SMALL -10
#define AARUF_ERROR_MEDIA_TAG_NOT_PRESENT -11
#define AARUF_ERROR_INCORRECT_MEDIA_TYPE -12
#define AARUF_ERROR_TRACK_NOT_FOUND -13
#define AARUF_ERROR_REACHED_UNREACHABLE_CODE -14
#define AARUF_ERROR_INVALID_TRACK_FORMAT -15
#define AARUF_ERROR_SECTOR_TAG_NOT_PRESENT -11

#define AARUF_STATUS_OK 0
#define AARUF_STATUS_SECTOR_NOT_DUMPED 1
#define AARUF_STATUS_SECTOR_WITH_ERRORS 2
#define AARUF_STATUS_SECTOR_DELETED 3

#endif // LIBAARUFORMAT_ERRORS_H
