//
// Created by claunia on 17/03/19.
//

#ifndef LIBDICFORMAT_ERRORS_H
#define LIBDICFORMAT_ERRORS_H

#define DICF_ERROR_NOT_DICFORMAT -1
#define DICF_ERROR_FILE_TOO_SMALL -2
#define DICF_ERROR_INCOMPATIBLE_VERSION -3
#define DICF_ERROR_CANNOT_READ_INDEX -4
#define DICF_ERROR_SECTOR_OUT_OF_BOUNDS -5
#define DICF_ERROR_CANNOT_READ_HEADER -6
#define DICF_ERROR_CANNOT_READ_BLOCK -7
#define DICF_ERROR_UNSUPPORTED_COMPRESSION -8

#endif //LIBDICFORMAT_ERRORS_H
