//
// Created by claunia on 17/03/19.
//

#ifndef LIBDICFORMAT_ERRORS_H
#define LIBDICFORMAT_ERRORS_H

#define DICF_ERROR_NOT_DICFORMAT -1
#define DICF_ERROR_FILE_TOO_SMALL -2
#define DICF_ERROR_INCOMPATIBLE_VERSION -3
#define DICF_ERROR_CANNOT_READ_INDEX -4

#endif //LIBDICFORMAT_ERRORS_H
