//
// Created by claunia on 17/03/19.
//

#ifndef LIBDICFORMAT_ERRORS_H
#define LIBDICFORMAT_ERRORS_H

#define DICF_ERROR_NOT_DICFORMAT -1
#define DICF_ERROR_FILE_TOO_SMALL -2
#define DICF_ERROR_INCOMPATIBLE_VERSION -3
#define DICF_ERROR_CANNOT_READ_INDEX -4
#define DICF_ERROR_SECTOR_OUT_OF_BOUNDS -5
#define DICF_ERROR_CANNOT_READ_HEADER -6
#define DICF_ERROR_CANNOT_READ_BLOCK -7
#define DICF_ERROR_UNSUPPORTED_COMPRESSION -8
#define DICF_ERROR_NOT_ENOUGH_MEMORY -9
#define DICF_ERROR_BUFFER_TOO_SMALL -10
#define DICF_ERROR_MEDIA_TAG_NOT_PRESENT -11
#define DICF_ERROR_INCORRECT_MEDIA_TYPE -12
#define DICF_ERROR_TRACK_NOT_FOUND -13
#define DICF_ERROR_REACHED_UNREACHABLE_CODE -14
#define DICF_ERROR_INVALID_TRACK_FORMAT -15
#define DICF_ERROR_SECTOR_TAG_NOT_PRESENT -11

#define DICF_STATUS_OK 0
#define DICF_STATUS_SECTOR_NOT_DUMPED 1
#define DICF_STATUS_SECTOR_WITH_ERRORS 2
#define DICF_STATUS_SECTOR_DELETED 3

#endif //LIBDICFORMAT_ERRORS_H
